# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TestPodFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPodFramework
  pod 'BigInt', '~> 3.0'
  pod 'MBProgressHUD'
  pod 'TrustKeystore', '~> 0.4.2'
  pod 'TrustCore', '~> 0.0.7'
  pod 'Result'
  pod 'IQKeyboardManager'

  target 'TestPodFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
